MIPS: Malta: Fix GCC 4.6.0 build error
  CC      arch/mips/mti-malta/malta-int.o
arch/mips/mti-malta/malta-int.c: In function ‘mips_pcibios_iack’:
arch/mips/mti-malta/malta-int.c:59:6: error: variable ‘dummy’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit ed35917478773e2364c6d29b38570b5b8f1a490c)