MIPS: IP22: Fix GCC 4.6.0 build error
  CC      arch/mips/sgi-ip22/ip22-time.o
arch/mips/sgi-ip22/ip22-time.c: In function ‘dosample’:
arch/mips/sgi-ip22/ip22-time.c:35:10: error: variable ‘lsb’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit df0e4a234413faa7ae38713196665665db6f8619)