[ALSA] AMD Au1x00: make driver build after cleanup
Modules: MIPS AU1x00 driver

AMD Au1x00 ALSA driver doesn't build after the recent code cleanup:

sound/mips/au1x00.c: In function 'au1000_setup_dma_link':
sound/mips/au1x00.c:173: error: 'pointer' undeclared (first use in this function)
sound/mips/au1x00.c:173: error: (Each undeclared identifier is reported only once
sound/mips/au1x00.c:173: error: for each function it appears in.)
sound/mips/au1x00.c: In function 'snd_au1000_hw_params':
sound/mips/au1x00.c:339: warning: implicit declaration of function 'snd_mask_min'

Signed-off-by: Takashi Iwai <tiwai@suse.de>
(cherry picked from commit d8327c784b51b57dac2c26cfad87dce0d68dfd98)