MIPS: tlbex: Fix build error on 64-bit.
  CC      arch/mips/mm/tlbex.o
/home/ralf/src/linux/linux-stable/arch/mips/mm/tlbex.c: In function ‘build_get_pgd_vmalloc64’:
/home/ralf/src/linux/linux-stable/arch/mips/mm/tlbex.c:602:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
cc1: all warnings being treated as errors

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit 952145e245e395c0296ea903071c93ddc8d16ba1)