MIPS: Alchemy: Quiet GCC-4.6 'set but not used' warning in plat_mem_setup
  CC      arch/mips/alchemy/common/setup.o
/home/ralf/src/linux/linux-stable/arch/mips/alchemy/common/setup.c: In function ‘plat_mem_setup’:
/home/ralf/src/linux/linux-stable/arch/mips/alchemy/common/setup.c:49:8: error: variable ‘argptr’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit f9085fcfc3ee03ce34b15f2c2f2d47f848da7869)