MIPS: Malta: Fix GCC 4.6.0 build error
  CC      arch/mips/mti-malta/malta-init.o
arch/mips/mti-malta/malta-init.c: In function ‘prom_init’:
arch/mips/mti-malta/malta-init.c:196:6: error: variable ‘result’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit a07fa912710b6c315f5e30ab464c9a6891419c71)