MIPS: SMP: Fix build error due to warning.
  CC      arch/mips/kernel/smp.o
/home/ralf/src/linux/linux-stable/arch/mips/kernel/smp.c: In function ‘smp_call_function_single’:
/home/ralf/src/linux/linux-stable/arch/mips/kernel/smp.c:249:6: error: variable ‘ret’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Fixed by passing on the error code in ret.

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>