[MIPS] EV96100: Fix over two year old typo in variable name.
  CC      arch/mips/galileo-boards/ev96100/irq.o
/home/ralf/src/linux/linux-stable/arch/mips/galileo-boards/ev96100/irq.c: In function ‘ev96100_cpu_irq’:
/home/ralf/src/linux/linux-stable/arch/mips/galileo-boards/ev96100/irq.c:59:14: error: ‘pending’ undeclared (first use in this function)
/home/ralf/src/linux/linux-stable/arch/mips/galileo-boards/ev96100/irq.c:59:14: note: each undeclared identifier is reported only once for each function it appears in
[...]
make[3]: *** [arch/mips/galileo-boards/ev96100/irq.o] Error 1

[ralf@linux-mips.org: and now that I'm cherrypickin this, over 8 years.]

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit 2ef2e1d9731bd8b3d8565e31bacd52a7c13a0aed)