MIPS: tlbex: Fix GCC 4.6.0 build error
  CC      arch/mips/mm/tlbex.o
arch/mips/mm/tlbex.c: In function ‘build_r4000_tlb_refill_handler’:
arch/mips/mm/tlbex.c:1155:22: error: variable ‘vmalloc_mode’ set but not used [-Werror=unused-but-set-variable]
arch/mips/mm/tlbex.c:1154:28: error: variable ‘htlb_info’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit 9fb8dc722caf832706ae1f446aa41b5a9ba6172b)
(cherry picked from commit 1da1a6a15eb39cfe341a1c332a76128c91b8edb1)