MIPS: Alchemy: Quiet GCC-4.6 'set but not used' warning in plat_irq_dispatch.
  CC      arch/mips/alchemy/common/irq.o
/home/ralf/src/linux/linux-stable/arch/mips/alchemy/common/irq.c: In function ‘plat_irq_dispatch’:
/home/ralf/src/linux/linux-stable/arch/mips/alchemy/common/irq.c:507:24: error: variable ‘bit’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Quiet the warning/error by marking bit as __maybe_unused.

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit b6229a32ac92492e1f04cc781f320ef0a6c2b7b4)