MIPS: MIPSsim: Fix build error.
  CC      arch/mips/mips-boards/sim/sim_mem.o
/home/ralf/src/linux/linux-stable/arch/mips/mips-boards/sim/sim_mem.c:106:60: error: conflicting types for ‘prom_free_prom_memory’
In file included from /home/ralf/src/linux/linux-stable/arch/mips/mips-boards/sim/sim_mem.c:25:0:
include2/asm/mips-boards/prom.h:39:51: note: previous declaration of ‘prom_free_prom_memory’ was here

Caused by 75943497b3b8976fda04171c27e789054be65863 [[MIPS] 34K SMTC merge.]

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>