MIPS: PowerTV: quiet GCC-4.6 'set but not used' warnings in prom_meminit.
  CC      arch/mips/powertv/memory.o
/home/ralf/src/linux/linux-stable/arch/mips/powertv/memory.c: In function ‘prom_meminit’:
/home/ralf/src/linux/linux-stable/arch/mips/powertv/memory.c:54:6: error: variable ‘high_mem’ set but not used [-Werror=unused-but-set-variable]
/home/ralf/src/linux/linux-stable/arch/mips/powertv/memory.c:51:15: error: variable ‘physend’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Fixed by deleting the variables and code to set them.

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit 937d8f4cfdb638510b08ff7814a705ec7ec10667)