MIPS: rbhma4200: Quiet GCC-4.6 'set but not used' warning in plat_mem_setup.
  CC      arch/mips/tx4927/toshiba_rbtx4927/toshiba_rbtx4927_irq.o
/home/ralf/src/linux/linux-stable/arch/mips/tx4927/toshiba_rbtx4927/toshiba_rbtx4927_irq.c: In function ‘toshiba_rbtx4927_irq_dump_pics’:
/home/ralf/src/linux/linux-stable/arch/mips/tx4927/toshiba_rbtx4927/toshiba_rbtx4927_irq.c:380:6: error: variable ‘level5_s’ set but not used [-Werror=unused-but-set-variable]
/home/ralf/src/linux/linux-stable/arch/mips/tx4927/toshiba_rbtx4927/toshiba_rbtx4927_irq.c:379:6: error: variable ‘level5_m’ set but not used [-Werror=unused-but-set-variable]
/home/ralf/src/linux/linux-stable/arch/mips/tx4927/toshiba_rbtx4927/toshiba_rbtx4927_irq.c:378:6: error: variable ‘level4_s’ set but not used [-Werror=unused-but-set-variable]
/home/ralf/src/linux/linux-stable/arch/mips/tx4927/toshiba_rbtx4927/toshiba_rbtx4927_irq.c:377:6: error: variable ‘level4_m’ set but not used [-Werror=unused-but-set-variable]
/home/ralf/src/linux/linux-stable/arch/mips/tx4927/toshiba_rbtx4927/toshiba_rbtx4927_irq.c:376:6: error: variable ‘level3_s’ set but not used [-Werror=unused-but-set-variable]
/home/ralf/src/linux/linux-stable/arch/mips/tx4927/toshiba_rbtx4927/toshiba_rbtx4927_irq.c:375:6: error: variable ‘level3_m’ set but not used [-Werror=unused-but-set-variable]
/home/ralf/src/linux/linux-stable/arch/mips/tx4927/toshiba_rbtx4927/toshiba_rbtx4927_irq.c:374:6: error: variable ‘level2_s’ set but not used [-Werror=unused-but-set-variable]
/home/ralf/src/linux/linux-stable/arch/mips/tx4927/toshiba_rbtx4927/toshiba_rbtx4927_irq.c:373:6: error: variable ‘level2_p’ set but not used [-Werror=unused-but-set-variable]
/home/ralf/src/linux/linux-stable/arch/mips/tx4927/toshiba_rbtx4927/toshiba_rbtx4927_irq.c:371:6: error: variable ‘level1_s’ set but not used [-Werror=unused-but-set-variable]
/home/ralf/src/linux/linux-stable/arch/mips/tx4927/toshiba_rbtx4927/toshiba_rbtx4927_irq.c:370:6: error: variable ‘level1_m’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit b7a74a193a4fba0aa28ac7260478036bc8106883)