MIPS: MT: Fix VPE loader built error.
  CC      arch/mips/kernel/vpe.o
/home/ralf/src/linux/linux-stable/arch/mips/kernel/vpe.c: In function ‘vpe_open’:
/home/ralf/src/linux/linux-stable/arch/mips/kernel/vpe.c:1102:10: error: ‘KERN_WARN’ undeclared (first use in this function)
/home/ralf/src/linux/linux-stable/arch/mips/kernel/vpe.c:1102:10: note: each undeclared identifier is reported only once for each function it appears in
/home/ralf/src/linux/linux-stable/arch/mips/kernel/vpe.c:1102:20: error: expected ‘)’ before string constant
/home/ralf/src/linux/linux-stable/arch/mips/kernel/vpe.c: At top level:
/home/ralf/src/linux/linux-stable/arch/mips/kernel/vpe.c:231:13: warning: ‘dump_mtregs’ defined but not used [-Wunused-function]
make[3]: *** [arch/mips/kernel/vpe.o] Error 1

Damage done by 5b91e86ee1fb165df0dfabd28860c9692b291203 [MIPS: VPE loader:
Check vmalloc return value in vpe_open].

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit 68c7e05f86bfc211b01cc7b9b0d2160c2b69cf9e)