MIPS: Fix build error.
Since 9b429dfad7a81cab4463ff4141349c58e40d8a47 there is a MIPS version of
div64_64() which duplicates the asm-generic version resulting in:

  CC      arch/mips/kernel/asm-offsets.s
In file included from /home/ralf/src/linux/linux-stable/include/linux/calc64.h:5:0,
                 from /home/ralf/src/linux/linux-stable/include/linux/jiffies.h:4,
                 from /home/ralf/src/linux/linux-stable/include/linux/sched.h:55,
                 from /home/ralf/src/linux/linux-stable/arch/mips/kernel/asm-offsets.c:14:
include2/asm/div64.h:66:24: error: redefinition of ‘div64_64’
In file included from include2/asm/div64.h:12:0,
                 from /home/ralf/src/linux/linux-stable/include/linux/calc64.h:5,
                 from /home/ralf/src/linux/linux-stable/include/linux/jiffies.h:4,
                 from /home/ralf/src/linux/linux-stable/include/linux/sched.h:55,
                 from /home/ralf/src/linux/linux-stable/arch/mips/kernel/asm-offsets.c:14:
/home/ralf/src/linux/linux-stable/include/asm-generic/div64.h:33:24: note: previous definition of ‘div64_64’ was here
make[3]: *** [arch/mips/kernel/asm-offsets.s] Error 1

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit ab8ceba4010a0587c9473ffe4fe23a5aad1764e7)