MIPS: Alchemy: Fix build error.
  CC      arch/mips/alchemy/common/irq.o
/home/ralf/src/linux/linux-stable/arch/mips/alchemy/common/irq.c: In function ‘restore_local_and_enable’:
/home/ralf/src/linux/linux-stable/arch/mips/alchemy/common/irq.c:261:23: error: variable ‘new_mask’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit fd2e91bde321a407b0b67635547998c330addff9)