MIPS: Fix build error of 32-bit kernels.
  CC      arch/mips/mm/tlbex.o
cc1: warnings being treated as errors
/home/ralf/src/linux/upstream-linus/arch/mips/mm/tlbex.c:172: error: ‘check_for_high_segbits’ defined but not used
make[3]: *** [arch/mips/mm/tlbex.o] Error 1

Introduced by 0f5317c1adce8525e93732cad8da5a2422abef80 "MIPS: Check for
accesses beyond the end of the PGD".

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit c301135980347ba706a2a0462eb35a227c1cfa98)