MIPS: SNI: Fix GCC 4.6.0 build error
  CC      arch/mips/sni/time.o
arch/mips/sni/time.c: In function ‘dosample’:
arch/mips/sni/time.c:98:19: error: variable ‘lsb’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit 1ff9946fdc245e9e71915296ca9debc6c496d596)