MIPS: IP32: Fix build error due to uninitialized variable.
  CC      arch/mips/sgi-ip32/ip32-reset.o
cc1: warnings being treated as errors
arch/mips/sgi-ip32/ip32-reset.c: In function ‘debounce’:
arch/mips/sgi-ip32/ip32-reset.c:97: error: ‘reg_a’ is used uninitialized in this function

The issues is old but due to the volatile keyword gcc older than 4.4 did
not warn about this obvious bug.

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit 63f7ec59053e3f850ab67a9938e631bcba64c6ce)